FROM ghost:3-alpine

# We need curl to download bootstrapper, we could also move this to previous build stage to keep this image cleaner.
RUN apk --no-cache add curl

# Add app-insights globally
RUN npm install -g applicationinsights
# Link app insights to avoid rebuild/validate projects npm package tree
RUN cd current && npm link applicationinsights 

RUN mkdir /opt/ai && curl -o /opt/ai/ai-bootstrap.js https://raw.githubusercontent.com/keyoke/Application-Insights-K8s-Codeless-Attach/master/agents/agents/2.8.33/nodejs/ai-bootstrap.js

# Configure AI via ENV VARS
# ENV APPINSIGHTS_INSTRUMENTATIONKEY xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
# ENV AI_CLOUD_ROLE Frontend
# ENV AI_CLOUD_ROLE_INSTANCE GhostInstance
# When hosting in Azure App Svc - Web App Container, add the following "Startup File" command "--require /opt/ai/ai-bootstrap.js"
# Or we could also use pre-load command "pm2 start --node-args='--require /opt/ai/ai-bootstrap.js'"
CMD ["node", "current/index.js", "--require /opt/ai/ai-bootstrap.js"]