FROM ghost:2-alpine
WORKDIR /var/lib/ghost/current

# Add app-insights globally
RUN npm install -g applicationinsights
# link app insights avoids projects npm package rebuild/validate
RUN npm link applicationinsights 

# Modify Ghost to Start monitoring
# process.env.APPINSIGHTS_INSTRUMENTATIONKEY
# ENV APPINSIGHTS_INSTRUMENTATIONKEY xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
RUN sed  -i.bak -e '/parentApp = express();/i appInsights = require("applicationinsights");' \
                -e '/parentApp = express();/i appInsights.setup().start();' index.js

